### PR TITLE
Fix error case in talisker_revision_id

### PR DESCRIPTION
**Pull request by nottrobin**
As pointed out by sparkiegeek:
https://github.com/canonical-ols/talisker/pull/262#discussion_r206055685

### CODE REVIEW

**Comment by nottrobin** [comment]
@sparkiegeek we can't just `return os.environ.get('TALISKER_REVISION_ID')` (
I initially implemented it that way, and then had multiple failing tests.), because the processing function expects a `bytes` type, not a UTF-8 `str`. So `return os.environ.get('TALISKER_REVISION_ID')` works in Python 2, but not 3.

So I think this PR is needed to make the function not produce an error.

**Comment by sparkiegeek** [comment]
@nottrobin ah, the `get()` does a `.decode()` and I misread it as a `.encode()` - ignore my previous comment.

**Comment by nottrobin** [comment]
@sparkiegeek you merged it! I was gonna make it better!

**Comment by sparkiegeek** [comment]
@nottrobin catching `AttributeError` does not count as 'better' :stuck_out_tongue:

**Pull request merged**
