### PR TITLE
checking system-specific error codes

### PR DESCRIPTION
**Pull request by IrSent**

### CODE REVIEW

**Comment by IrSent** [comment]
@bloodearnest I've sent the agreement form using your link (Used your name as contact).

**Comment by IrSent** [comment]
https://travis-ci.org/canonical-ols/talisker/jobs/537901443

**Comment by bloodearnest** [comment]
Thanks! Can you add yourself to the AUTHORS.rst file with the email you used for signing the CLA?

**Comment by IrSent** [comment]
> Thanks! Can you add yourself to the AUTHORS.rst file with the email you used for signing the CLA?

sure.

**Pull request merged**
