### PR TITLE
Release v0.21.4

### PR DESCRIPTION
**Pull request by maxiberta**
Bumps supported django version to 4.x.

### CODE REVIEW

**Review by shanepelletier — APPROVED** [review]
LGTM, thanks!!

**Comment by SuperAlpaca27** [comment]
+1, thanks!

The Read the Docs build seems to fail, probably because of the indent for the `python` part at the end of `.readthedocs.yaml`, but maybe that can be tackled later?

**Review by SuperAlpaca27 — APPROVED** [review]

**Review by shanepelletier — APPROVED** [review]
Re-approving to try to fix merging.

**Comment by jugmac00** [comment]
For the broken docs, please see https://github.com/canonical-ols/talisker/pull/605

**Comment by maxiberta** [comment]
> For the broken docs, please see #605

Oh, I'll take a look if possible! But in the meantime, can we maybe get this one merged please? Docs should not block merges afaict. Thx!

**Review by suligap — APPROVED** [review]
Thanks!

**Pull request merged**
